### ISSUE TITLE
r-irodsclient package? 

### ISSUE THREAD

**Issue by LiNk-NY** [irods/r-irodsclient#4]
Hi @JustinKyleJames, 
Thanks for the work you're doing here. 
I would find an iRods R interface very useful. 

Is this intended to be an R package? 

Regards, 
Marcel

**Comment by JustinKyleJames** [comment]
This is just a wrapper to make access to the iRODS REST interface easier from R.  There is no plan right now to make this into an R package.  For the time being you would have to just include the source file and of course this does have a dependency on the iRODS REST interface.

There is a project underway to make an R client using the native C iRODS client code.  This has not yet been released.

**Comment by LiNk-NY** [comment]
If you would like, I can transform this into a package for use, for the time being. 
Regards,
Marcel

**Comment by burnce** [comment]
Hello Marcel,

Please take a look at the following:
https://irods.org/uploads/2016/12/irods_ugm2016_proceedings.pdf
(page 31)

Preview source is currently available at:
http://irods.org/wp-content/uploads/2016/06/rirods_1.0.tar.gz

Best regards,

Bernhard

**Comment by Danny-dK** [comment]
Considering the last commit and messages, I'm assuming this has all been abandoned? That would be a shame considering the number of people using R. It would be very helpful is this would maintained and updated.

**Comment by trel** [comment]
@Danny-dK  This is not abandoned - just fell away from being a priority and we had a hard time getting it supported/tested in our CI configuration.

It builds and passes manually - happy to hear if it builds and works for you.

**Comment by trel** [comment]
Archiving this repository.

Please find new work at https://github.com/irods/irods_client_library_rirods.
